### ISSUE TITLE
Object knox has no method 'createClient'

### ISSUE THREAD

**Issue by pxwise** [LearnBoost/knox#272]
First time using knox v0.9.2, with code:

```javascript
var knox = ('knox');

var client = knox.createClient({
    key: 'key',
    secret: 'secret-key',
    bucket: 'bucketname'
});
```
Correct key, secret key and bucketname were filled in.

Receive Object knox has no method 'createClient'.

**Comment by danielsarsi** [comment]
You load modules by calling ``require();``, like this:
```javascript
var knox = require('knox');
```

**Comment by pxwise** [comment]
Obvious mistake. thanks.
